server:
  port: 8081

person:
  name: wcs
  age: 24
  map: {k1: a,k2: b}
  list:
    - one
    - two
  dog:
    name: dog
    age: 2

#logging:
#  path: /spring/log
#  level:
#    com:
#      example: debug
