server:
  port: 8081

person:
  name: wcs
  age: 24
  map: {k1: a,k2: b}
  list:
    - one
    - two
  dog:
    name: dog
    age: 2

    #logging:
    #  path: /spring/log
    #  level:
    #    com:
    #      example: debug



spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.2.100:3306/jdbc
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      validation-query: SELECT 1
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 300000
      numTestsPerEvictionRun: 20
      minEvictableIdleTimeMillis: 3600000
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

